/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "InterfaceClienteServidorModulos.h"
#include <stdbool.h>

struct modulo
{
	bool ocupado;
	int numeroTurno;
	char identificacionUsuario[MAXIDENTIFICACION];
};
typedef struct modulo modulo;

struct usuario
{
	char identificacionUsuario[MAXIDENTIFICACION];
};
typedef struct usuario usuario;

int numeroTurno = 1;
int cantidadUsuariosFila = 0;
modulo vectorModulo[3];
usuario filaVirtual[10];

int consultarNumeroModulosDisponible();

nodo_turno *generarturno_1_svc(char **argp, struct svc_req *rqstp)
{
	static nodo_turno result;

	int posicion = consultarNumeroModulosDisponible();
	printf("\n");
	return &result;
}
